Models/Sushi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SilliconSushi.Models
{
    public class Sushi
    {   
        [Key]
        public int SushiId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }

        [Required]
        public bool InStock { get; set; }

        [Required]
        public string ImageUrl { get; set; }

        public string Allergy { get; set; }

        public bool SushiOfTheDay { get; set; }

    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using SilliconSushi.Models;
using SilliconSushi.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SilliconSushi.Controllers
{
    public class ShoppingCartController: Controller
    {
        private readonly ShoppingCart _shoppingCart;
        private readonly ISushiRepository _sushiRepository;

       public ShoppingCartController(ShoppingCart shoppingCart, ISushiRepository sushiRepository)
        {
            _shoppingCart = shoppingCart;
            _sushiRepository = sushiRepository;
        }

        public IActionResult Index()
        {
            var cartViewModel = new CartViewModel();
            cartViewModel.shoppingCartItems = _shoppingCart.GetCartItems();
            cartViewModel.totalPrice = _shoppingCart.GetTotalPrice();

            return View(cartViewModel);
        }

        public RedirectToActionResult AddToCart(int sushiId)
        {
            var selectedSushi = _sushiRepository.AllSushi.FirstOrDefault(s => s.SushiId == sushiId);

            if( selectedSushi != null)
            {
                _shoppingCart.AddToShoppingCart(selectedSushi, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromCart(int sushiId)
        {
            var selectedSushi = _sushiRepository.AllSushi.FirstOrDefault(s => s.SushiId == sushiId);

            if (selectedSushi != null)
            {
                _shoppingCart.RemoveFromShoppingCart(selectedSushi, 1);
            }

            return RedirectToAction("Index");
        }


    }
}

Controllers/SushiController.cs
using Microsoft.AspNetCore.Mvc;
using SilliconSushi.Models;
using SilliconSushi.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SilliconSushi.Controllers
{
    public class SushiController : Controller
    {
        private readonly ISushiRepository _sushiRepository;
        private readonly ICategoryRepository _categoryRepository;

        public SushiController(ISushiRepository sushiRepository, ICategoryRepository categoryRepository)
        {
            _sushiRepository = sushiRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            HomeViewModel homeViewModel = new HomeViewModel {
                SushiOfTheDay = _sushiRepository.TopSushi
            };

            return View(homeViewModel);
        }

        public IActionResult AllSushi()
        {
            SushiListViewModel sushiListView = new SushiListViewModel();
            sushiListView.Sushis = _sushiRepository.AllSushi;
            sushiListView.CurrentCategory = "Vegetarian";

            return View(sushiListView);
        }

        public IActionResult Details(int id)
        {
            var sushi = _sushiRepository.getSushiById(id);

            if (sushi == null)
                return NotFound();

            return View(sushi);
        }
    }
}

Views/Sushi/AllSushi.cshtml
@model SushiListViewModel

<h1>@Model.CurrentCategory</h1>

<div class="row">
    @foreach(var sushi in Model.Sushis)
    {
        <partial name="_SushiCard" model="sushi" />
    }

</div>

Views/Sushi/Details.cshtml
@model Sushi

<div class="thumbnail">
    <h3>@Model.Name</h3>

    <img src="@Model.ImageUrl" class="thumbnailImg" />

    <div class="caption-full customView">
        <h3 class="float-end">@Model.Price.ToString("C")</h3>
        <h3>
            <a asp-controller="Sushi"
               asp-action="Details"
               asp-route-id="@Model.SushiId">@Model.Name</a>
        </h3>
        <p>@Model.ShortDescription</p>
        <p>@Model.LongDescription</p>

        <div class="addToCart">
            <p> <a class="btn btn-primary" 
                   asp-controller="ShoppingCart" 
                   asp-action="AddToCart" asp-route-sushiId="@Model.SushiId">Add to cart </a></p>
        </div>
    </div>
    
</div>

Views/Sushi/Index.cshtml
@model HomeViewModel

<partial name="_Carousel" />

<h2> Sushi of the Day: </h2>

<div class="row">
    
        @foreach (var sushi in Model.SushiOfTheDay)
        {
           <partial name="_SushiCard" model="sushi" />
        }
</div>